version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-typeahead
    container_name: frontend-typehead
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /app/node_modules
