version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontent-typeahead
    container_name: frontend-typehead
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
networks:
    app-network:
        driver: bridge
